version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - .net
    groups:
      all-nuget:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    groups:
      all-docker:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
    groups:
      all-actions:
        patterns:
          - "*"
