// <auto-generated />
using System;
using System.Collections.Generic;
using Wallow.Showcases.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Wallow.Showcases.Infrastructure.Migrations;

[DbContext(typeof(ShowcasesDbContext))]
partial class ShowcasesDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("showcases")
            .HasAnnotation("ProductVersion", "10.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Wallow.Showcases.Domain.Entities.Showcase", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("Category")
                    .HasColumnType("integer")
                    .HasColumnName("category");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("DemoUrl")
                    .HasColumnType("text")
                    .HasColumnName("demo_url");

                b.Property<string>("Description")
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<int>("DisplayOrder")
                    .HasColumnType("integer")
                    .HasColumnName("display_order");

                b.Property<string>("GitHubUrl")
                    .HasColumnType("text")
                    .HasColumnName("github_url");

                b.Property<bool>("IsPublished")
                    .HasColumnType("boolean")
                    .HasColumnName("is_published");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("title");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.Property<string>("VideoUrl")
                    .HasColumnType("text")
                    .HasColumnName("video_url");

                b.PrimitiveCollection<List<string>>("_tags")
                    .IsRequired()
                    .HasColumnType("text[]")
                    .HasColumnName("tags");

                b.HasKey("Id");

                b.ToTable("showcases", "showcases");
            });
#pragma warning restore 612, 618
    }
}
