apiVersion: v1
kind: Secret
metadata:
  name: wallow-secrets
type: Opaque
data:
  ConnectionStrings__DefaultConnection: CHANGEME_BASE64
  ConnectionStrings__Redis: CHANGEME_BASE64
  ConnectionStrings__RabbitMq: CHANGEME_BASE64
