/*
 * Public-API pin for Wallow-m5aq.1.3 (migrate the flat components into
 * per-component folders).
 *
 * Task 1.3 is a MECHANICAL MOVE: every component file relocates from
 * `src/<name>.tsx` to `src/components/<name>/<name>.tsx`, each folder grows an
 * `index.ts`, and the root barrel is rewritten to re-export the folders instead
 * of the files. The acceptance criteria say that move must produce "no behavior
 * change to the public API" — this spec is what makes that claim checkable
 * rather than asserted.
 *
 * It therefore PASSES BEFORE the migration as well as after (see the red-phase
 * note on the bead): it is an invariant guard, not a new-structure assertion.
 * A migration that silently drops an export while rewriting the barrel — the
 * single most likely way this "zero risk" restructure actually breaks the apps —
 * turns this file red. It is now the ONLY pin on the catalog set:
 * `core/package-scaffold.test.ts` and `core/dist-structure.test.ts` walked the
 * folder tree and `dist/` off disk, and went with the source-reading guards
 * (`Wallow-xg9t.1`).
 *
 * Two surfaces are pinned, because the barrel re-exports both:
 *   - runtime values (components + the two exported constants), checked here;
 *   - types, checked at COMPILE time by `PublicTypeExports` at the bottom.
 *     `tsconfig.json` includes all of `src`, so `pnpm --filter
 *     @bc-solutions-coder/ui typecheck` fails if a `type` re-export is lost —
 *     something no runtime assertion can see.
 *
 * This is a pure-logic `*.test.ts`, so it runs in the vitest NODE project. It
 * only imports the module graph (no rendering), which is safe: none of the
 * components run DOM work at module scope — they touch `document` from
 * `useEffect` only.
 */

import { describe, expect, it } from "vitest";

import * as ui from "./index";

import type {
  AccordionHeaderProps,
  AccordionItemProps,
  AccordionPanelProps,
  AccordionRootProps,
  AccordionTriggerProps,
  AlertDialogBackdropProps,
  AlertDialogCloseProps,
  AlertDialogDescriptionProps,
  AlertDialogPopupProps,
  AlertDialogPortalProps,
  AlertDialogRootProps,
  AlertDialogTitleProps,
  AlertDialogTriggerProps,
  AlertDialogViewportProps,
  AutocompleteArrowProps,
  AutocompleteBackdropProps,
  AutocompleteClearProps,
  AutocompleteCollectionProps,
  AutocompleteEmptyProps,
  AutocompleteGroupLabelProps,
  AutocompleteGroupProps,
  AutocompleteIconProps,
  AutocompleteInputGroupProps,
  AutocompleteInputProps,
  AutocompleteItemProps,
  AutocompleteListProps,
  AutocompletePopupProps,
  AutocompletePortalProps,
  AutocompletePositionerProps,
  AutocompleteRootProps,
  AutocompleteRowProps,
  AutocompleteSeparatorProps,
  AutocompleteStatusProps,
  AutocompleteTriggerProps,
  AutocompleteValueProps,
  AvatarFallbackProps,
  AvatarImageProps,
  AvatarRootProps,
  BadgeProps,
  ButtonProps,
  ButtonVariant,
  CardProps,
  CardTitleProps,
  CenteredCardLayoutProps,
  CheckboxGroupProps,
  CheckboxIndicatorProps,
  CheckboxRootProps,
  CollapsiblePanelProps,
  CollapsibleRootProps,
  CollapsibleTriggerProps,
  ComboboxArrowProps,
  ComboboxBackdropProps,
  ComboboxChipProps,
  ComboboxChipRemoveProps,
  ComboboxChipsProps,
  ComboboxClearProps,
  ComboboxCollectionProps,
  ComboboxEmptyProps,
  ComboboxGroupLabelProps,
  ComboboxGroupProps,
  ComboboxIconProps,
  ComboboxInputGroupProps,
  ComboboxInputProps,
  ComboboxItemIndicatorProps,
  ComboboxItemProps,
  ComboboxLabelProps,
  ComboboxListProps,
  ComboboxPopupProps,
  ComboboxPortalProps,
  ComboboxPositionerProps,
  ComboboxRootProps,
  ComboboxRowProps,
  ComboboxSeparatorProps,
  ComboboxStatusProps,
  ComboboxTriggerProps,
  ComboboxValueProps,
  ContextMenuArrowProps,
  ContextMenuBackdropProps,
  ContextMenuCheckboxItemIndicatorProps,
  ContextMenuCheckboxItemProps,
  ContextMenuGroupLabelProps,
  ContextMenuGroupProps,
  ContextMenuItemProps,
  ContextMenuLinkItemProps,
  ContextMenuPopupProps,
  ContextMenuPortalProps,
  ContextMenuPositionerProps,
  ContextMenuRadioGroupProps,
  ContextMenuRadioItemIndicatorProps,
  ContextMenuRadioItemProps,
  ContextMenuRootProps,
  ContextMenuSeparatorProps,
  ContextMenuSubmenuRootProps,
  ContextMenuSubmenuTriggerProps,
  ContextMenuTriggerProps,
  DialogBackdropProps,
  DialogCloseProps,
  DialogDescriptionProps,
  DialogPopupProps,
  DialogPortalProps,
  DialogRootProps,
  DialogTitleProps,
  DialogTriggerProps,
  DialogViewportProps,
  DocumentStylesProps,
  DrawerBackdropProps,
  DrawerCloseProps,
  DrawerContentProps,
  DrawerDescriptionProps,
  DrawerIndentBackgroundProps,
  DrawerIndentProps,
  DrawerPopupProps,
  DrawerPortalProps,
  DrawerProviderProps,
  DrawerRootProps,
  DrawerSwipeAreaProps,
  DrawerTitleProps,
  DrawerTriggerProps,
  DrawerViewportProps,
  DrawerVirtualKeyboardProviderProps,
  EmptyStateProps,
  ErrorBannerProps,
  FieldControlProps,
  FieldDescriptionProps,
  FieldErrorProps,
  FieldItemProps,
  FieldLabelProps,
  FieldProps,
  FieldRootProps,
  FieldsetLegendProps,
  FieldsetProps,
  FieldsetRootProps,
  FieldValidityProps,
  ForkAttributionProps,
  FormActions,
  FormErrors,
  FormProps,
  FormSubmitEventDetails,
  FormValidationMode,
  InputProps,
  LabelProps,
  ListCardProps,
  ListRowProps,
  MenuArrowProps,
  MenuBackdropProps,
  MenubarProps,
  MenuCheckboxItemIndicatorProps,
  MenuCheckboxItemProps,
  MenuGroupLabelProps,
  MenuGroupProps,
  MenuItemProps,
  MenuLinkItemProps,
  MenuPopupProps,
  MenuPortalProps,
  MenuPositionerProps,
  MenuRadioGroupProps,
  MenuRadioItemIndicatorProps,
  MenuRadioItemProps,
  MenuRootProps,
  MenuSeparatorProps,
  MenuSubmenuRootProps,
  MenuSubmenuTriggerProps,
  MenuTriggerProps,
  MenuViewportProps,
  MeterIndicatorProps,
  MeterLabelProps,
  MeterRootProps,
  MeterTrackProps,
  MeterValueProps,
  MutedTextProps,
  NavigationMenuArrowProps,
  NavigationMenuBackdropProps,
  NavigationMenuContentProps,
  NavigationMenuIconProps,
  NavigationMenuItemProps,
  NavigationMenuLinkProps,
  NavigationMenuListProps,
  NavigationMenuPopupProps,
  NavigationMenuPortalProps,
  NavigationMenuPositionerProps,
  NavigationMenuRootProps,
  NavigationMenuTriggerProps,
  NavigationMenuViewportProps,
  NumberFieldDecrementProps,
  NumberFieldGroupProps,
  NumberFieldIncrementProps,
  NumberFieldInputProps,
  NumberFieldRootProps,
  NumberFieldScrubAreaCursorProps,
  NumberFieldScrubAreaProps,
  OTPFieldInputProps,
  OTPFieldRootProps,
  OTPFieldSeparatorProps,
  PageContainerProps,
  PageHeaderProps,
  PopoverArrowProps,
  PopoverBackdropProps,
  PopoverCloseProps,
  PopoverDescriptionProps,
  PopoverPopupProps,
  PopoverPortalProps,
  PopoverPositionerProps,
  PopoverRootProps,
  PopoverTitleProps,
  PopoverTriggerProps,
  PopoverViewportProps,
  PreviewCardArrowProps,
  PreviewCardBackdropProps,
  PreviewCardPopupProps,
  PreviewCardPortalProps,
  PreviewCardPositionerProps,
  PreviewCardRootProps,
  PreviewCardTriggerProps,
  PreviewCardViewportProps,
  ProgressIndicatorProps,
  ProgressLabelProps,
  ProgressRootProps,
  ProgressStatus,
  ProgressTrackProps,
  ProgressValueProps,
  RadioGroupOrientation,
  RadioGroupProps,
  RadioIndicatorProps,
  RadioRootProps,
  ScrollAreaContentProps,
  ScrollAreaCornerProps,
  ScrollAreaRootProps,
  ScrollAreaScrollbarProps,
  ScrollAreaThumbProps,
  ScrollAreaViewportProps,
  SelectArrowProps,
  SelectBackdropProps,
  SelectGroupLabelProps,
  SelectGroupProps,
  SelectIconProps,
  SelectItemIndicatorProps,
  SelectItemProps,
  SelectItemTextProps,
  SelectLabelProps,
  SelectListProps,
  SelectPopupProps,
  SelectPortalProps,
  SelectPositionerProps,
  SelectRootProps,
  SelectScrollDownArrowProps,
  SelectScrollUpArrowProps,
  SelectSeparatorProps,
  SelectTriggerProps,
  SelectValueProps,
  SeparatorProps,
  SimpleSelectOption,
  SimpleSelectProps,
  SliderControlProps,
  SliderIndicatorProps,
  SliderLabelProps,
  SliderRootProps,
  SliderThumbProps,
  SliderTrackProps,
  SliderValueProps,
  SwitchRootProps,
  SwitchThumbProps,
  TabsIndicatorProps,
  TabsListProps,
  TabsPanelProps,
  TabsRootProps,
  TabsTabProps,
  TextProps,
  TextareaProps,
  ThemeContextValue,
  ThemeMode,
  ThemePreference,
  ThemeProviderProps,
  ThemeResolutionInput,
  ThemeScriptProps,
  ThemeToggleProps,
  ToastActionProps,
  ToastArrowProps,
  ToastCloseProps,
  ToastContentProps,
  ToastDescriptionProps,
  ToastManager,
  ToastManagerAddOptions,
  ToastManagerPromiseOptions,
  ToastManagerUpdateOptions,
  ToastNamespace,
  ToastObject,
  ToastPortalProps,
  ToastPositionerProps,
  ToastProviderProps,
  ToastRootProps,
  ToastTitleProps,
  ToastViewportProps,
  ToggleGroupProps,
  ToggleProps,
  ToolbarButtonProps,
  ToolbarGroupProps,
  ToolbarInputProps,
  ToolbarLinkProps,
  ToolbarRootProps,
  ToolbarSeparatorProps,
  TooltipArrowProps,
  TooltipPopupProps,
  TooltipPortalProps,
  TooltipPositionerProps,
  TooltipProviderProps,
  TooltipRootProps,
  TooltipTriggerProps,
  TooltipViewportProps,
  UseToastManagerReturnValue,
} from "./index";

/**
 * The complete runtime surface of `@bc-solutions-coder/ui`, sorted. Asserted as
 * an EXACT set (not a subset) in both directions: a dropped export fails, and so
 * does an accidentally widened one — nothing reaches the barrel by accident,
 * `core/cn.ts` included (it is an internal helper components reach by relative
 * path; see Wallow-m5aq.1.2).
 *
 * Each Base UI wave grows this list once, at its gate, in lockstep with
 * `src/index.ts` — the two are what the catalog is, now that nothing walks
 * `src/components` off disk.
 * Components only: a component's CVA recipe is public on its own subpath
 * (`@bc-solutions-coder/ui/<name>`) and deliberately absent here.
 */
const PUBLIC_RUNTIME_EXPORTS = [
  "Accordion",
  "AlertDialog",
  "Autocomplete",
  "Avatar",
  "Badge",
  "Button",
  "Card",
  "CardTitle",
  "CenteredCardLayout",
  "Checkbox",
  "CheckboxGroup",
  "Collapsible",
  "Combobox",
  "ContextMenu",
  "Dialog",
  "DocumentStyles",
  "Drawer",
  "EmptyState",
  "ErrorBanner",
  "Field",
  "Fieldset",
  "FocusOnNavigate",
  "ForkAttribution",
  "Form",
  "Input",
  "Label",
  "ListCard",
  "ListRow",
  "MAIN_HEADING_SELECTOR",
  "Menu",
  "Menubar",
  "Meter",
  "MutedText",
  "NavigationMenu",
  "NumberField",
  "OTPField",
  "PageContainer",
  "PageHeader",
  "Popover",
  "PreviewCard",
  "Progress",
  "READY_ATTRIBUTE",
  "Radio",
  "RadioGroup",
  "ReadyIndicator",
  "ScrollArea",
  "Select",
  "Separator",
  "SimpleSelect",
  "Slider",
  "Switch",
  "THEME_PREFERENCE_CYCLE",
  "THEME_STORAGE_KEY",
  "Tabs",
  "Text",
  "Textarea",
  "ThemeProvider",
  "ThemeScript",
  "ThemeToggle",
  "Toast",
  "Toggle",
  "ToggleGroup",
  "Toolbar",
  "Tooltip",
  "createToastManager",
  "resolveThemeMode",
  "themeInitScript",
  "useTheme",
  "useToastManager",
];

/**
 * The barrel's exported constants, plus the entry points that are plain
 * functions rather than components: the two Toast ones — `useToastManager` (a
 * hook) and `createToastManager` (a manager factory for use outside React) — and
 * theme-provider's `useTheme` hook alongside the two pure helpers the pre-paint
 * script and the provider share (`resolveThemeMode`, `themeInitScript`).
 * `THEME_PREFERENCE_CYCLE` is an array constant, so it needs listing for the
 * same reason `READY_ATTRIBUTE` does. Everything else on the barrel is a
 * component.
 */
const NON_COMPONENT_EXPORTS = new Set([
  "MAIN_HEADING_SELECTOR",
  "READY_ATTRIBUTE",
  "THEME_PREFERENCE_CYCLE",
  "THEME_STORAGE_KEY",
  "createToastManager",
  "resolveThemeMode",
  "themeInitScript",
  "useTheme",
  "useToastManager",
]);

/**
 * Whether React would accept `value` as a component type. Plain function
 * components qualify, and so do the exotic objects `forwardRef`/`memo` return —
 * Base UI hands back a few of those (e.g. `Select.Portal`), and they are every
 * bit as renderable as a function.
 */
function isRenderable(value: unknown): boolean {
  if (typeof value === "function") {
    return true;
  }

  return typeof value === "object" && value !== null && "$$typeof" in value;
}

describe("@bc-solutions-coder/ui public API", () => {
  it("exports exactly the documented runtime surface", () => {
    expect(Object.keys(ui).toSorted()).toEqual(PUBLIC_RUNTIME_EXPORTS);
  });

  it("still exports every component as something React can render", () => {
    // Two shapes are legitimate. A single-part component is renderable on its
    // own. A compound one (Select, Slider, Checkbox, ...) is a namespace object
    // whose every member is a renderable part — `Select.Root`,
    // `Select.Trigger`. A stray constant or an empty object is a mistake, so the
    // namespace case still demands at least one part and checks each of them.
    const components = PUBLIC_RUNTIME_EXPORTS.filter((name) => !NON_COMPONENT_EXPORTS.has(name));

    for (const name of components) {
      const exported = (ui as Record<string, unknown>)[name];

      if (!isRenderable(exported)) {
        expect(typeof exported, name).toBe("object");

        const parts = Object.entries(exported as Record<string, unknown>);
        expect(parts.length, `${name} parts`).toBeGreaterThan(0);

        for (const [part, value] of parts) {
          expect(isRenderable(value), `${name}.${part}`).toBe(true);
        }
      }
    }
  });

  it("keeps the E2E hydration marker and heading selector constants intact", () => {
    // READY_ATTRIBUTE is load-bearing for EVERY Playwright suite in the repo
    // (`[data-app-ready='true']`), so its VALUE is pinned, not just its
    // presence — a folder move must not touch it.
    expect(ui.READY_ATTRIBUTE).toBe("data-app-ready");
    expect(ui.MAIN_HEADING_SELECTOR).toBe("h1");
  });
});

/**
 * Compile-time-only pin of the barrel's `type` re-exports. Referencing each one
 * in a tuple makes `tsc --noEmit` fail if the migration drops a `type` line from
 * `src/index.ts`; the alias is exported so it does not read as an unused local.
 */
export type PublicTypeExports = [
  AccordionHeaderProps,
  AccordionItemProps,
  AccordionPanelProps,
  AccordionRootProps,
  AccordionTriggerProps,
  AlertDialogBackdropProps,
  AlertDialogCloseProps,
  AlertDialogDescriptionProps,
  AlertDialogPopupProps,
  AlertDialogPortalProps,
  AlertDialogRootProps,
  AlertDialogTitleProps,
  AlertDialogTriggerProps,
  AlertDialogViewportProps,
  AutocompleteArrowProps,
  AutocompleteBackdropProps,
  AutocompleteClearProps,
  AutocompleteCollectionProps,
  AutocompleteEmptyProps,
  AutocompleteGroupLabelProps,
  AutocompleteGroupProps,
  AutocompleteIconProps,
  AutocompleteInputGroupProps,
  AutocompleteInputProps,
  AutocompleteItemProps,
  AutocompleteListProps,
  AutocompletePopupProps,
  AutocompletePortalProps,
  AutocompletePositionerProps,
  AutocompleteRootProps,
  AutocompleteRowProps,
  AutocompleteSeparatorProps,
  AutocompleteStatusProps,
  AutocompleteTriggerProps,
  AutocompleteValueProps,
  AvatarFallbackProps,
  AvatarImageProps,
  AvatarRootProps,
  BadgeProps,
  ButtonProps,
  ButtonVariant,
  CardProps,
  CardTitleProps,
  CenteredCardLayoutProps,
  CheckboxGroupProps,
  CheckboxIndicatorProps,
  CheckboxRootProps,
  CollapsiblePanelProps,
  CollapsibleRootProps,
  CollapsibleTriggerProps,
  ComboboxArrowProps,
  ComboboxBackdropProps,
  ComboboxChipProps,
  ComboboxChipRemoveProps,
  ComboboxChipsProps,
  ComboboxClearProps,
  ComboboxCollectionProps,
  ComboboxEmptyProps,
  ComboboxGroupLabelProps,
  ComboboxGroupProps,
  ComboboxIconProps,
  ComboboxInputGroupProps,
  ComboboxInputProps,
  ComboboxItemIndicatorProps,
  ComboboxItemProps,
  ComboboxLabelProps,
  ComboboxListProps,
  ComboboxPopupProps,
  ComboboxPortalProps,
  ComboboxPositionerProps,
  ComboboxRootProps,
  ComboboxRowProps,
  ComboboxSeparatorProps,
  ComboboxStatusProps,
  ComboboxTriggerProps,
  ComboboxValueProps,
  ContextMenuArrowProps,
  ContextMenuBackdropProps,
  ContextMenuCheckboxItemIndicatorProps,
  ContextMenuCheckboxItemProps,
  ContextMenuGroupLabelProps,
  ContextMenuGroupProps,
  ContextMenuItemProps,
  ContextMenuLinkItemProps,
  ContextMenuPopupProps,
  ContextMenuPortalProps,
  ContextMenuPositionerProps,
  ContextMenuRadioGroupProps,
  ContextMenuRadioItemIndicatorProps,
  ContextMenuRadioItemProps,
  ContextMenuRootProps,
  ContextMenuSeparatorProps,
  ContextMenuSubmenuRootProps,
  ContextMenuSubmenuTriggerProps,
  ContextMenuTriggerProps,
  DialogBackdropProps,
  DialogCloseProps,
  DialogDescriptionProps,
  DialogPopupProps,
  DialogPortalProps,
  DialogRootProps,
  DialogTitleProps,
  DialogTriggerProps,
  DialogViewportProps,
  DocumentStylesProps,
  DrawerBackdropProps,
  DrawerCloseProps,
  DrawerContentProps,
  DrawerDescriptionProps,
  DrawerIndentBackgroundProps,
  DrawerIndentProps,
  DrawerPopupProps,
  DrawerPortalProps,
  DrawerProviderProps,
  DrawerRootProps,
  DrawerSwipeAreaProps,
  DrawerTitleProps,
  DrawerTriggerProps,
  DrawerViewportProps,
  DrawerVirtualKeyboardProviderProps,
  EmptyStateProps,
  ErrorBannerProps,
  FieldControlProps,
  FieldDescriptionProps,
  FieldErrorProps,
  FieldItemProps,
  FieldLabelProps,
  FieldProps,
  FieldRootProps,
  FieldsetLegendProps,
  FieldsetProps,
  FieldsetRootProps,
  FieldValidityProps,
  ForkAttributionProps,
  FormActions,
  FormErrors,
  FormProps,
  FormSubmitEventDetails,
  FormValidationMode,
  InputProps,
  LabelProps,
  ListCardProps,
  ListRowProps,
  MenuArrowProps,
  MenuBackdropProps,
  MenubarProps,
  MenuCheckboxItemIndicatorProps,
  MenuCheckboxItemProps,
  MenuGroupLabelProps,
  MenuGroupProps,
  MenuItemProps,
  MenuLinkItemProps,
  MenuPopupProps,
  MenuPortalProps,
  MenuPositionerProps,
  MenuRadioGroupProps,
  MenuRadioItemIndicatorProps,
  MenuRadioItemProps,
  MenuRootProps,
  MenuSeparatorProps,
  MenuSubmenuRootProps,
  MenuSubmenuTriggerProps,
  MenuTriggerProps,
  MenuViewportProps,
  MeterIndicatorProps,
  MeterLabelProps,
  MeterRootProps,
  MeterTrackProps,
  MeterValueProps,
  MutedTextProps,
  NavigationMenuArrowProps,
  NavigationMenuBackdropProps,
  NavigationMenuContentProps,
  NavigationMenuIconProps,
  NavigationMenuItemProps,
  NavigationMenuLinkProps,
  NavigationMenuListProps,
  NavigationMenuPopupProps,
  NavigationMenuPortalProps,
  NavigationMenuPositionerProps,
  NavigationMenuRootProps,
  NavigationMenuTriggerProps,
  NavigationMenuViewportProps,
  NumberFieldDecrementProps,
  NumberFieldGroupProps,
  NumberFieldIncrementProps,
  NumberFieldInputProps,
  NumberFieldRootProps,
  NumberFieldScrubAreaCursorProps,
  NumberFieldScrubAreaProps,
  OTPFieldInputProps,
  OTPFieldRootProps,
  OTPFieldSeparatorProps,
  PageContainerProps,
  PageHeaderProps,
  PopoverArrowProps,
  PopoverBackdropProps,
  PopoverCloseProps,
  PopoverDescriptionProps,
  PopoverPopupProps,
  PopoverPortalProps,
  PopoverPositionerProps,
  PopoverRootProps,
  PopoverTitleProps,
  PopoverTriggerProps,
  PopoverViewportProps,
  PreviewCardArrowProps,
  PreviewCardBackdropProps,
  PreviewCardPopupProps,
  PreviewCardPortalProps,
  PreviewCardPositionerProps,
  PreviewCardRootProps,
  PreviewCardTriggerProps,
  PreviewCardViewportProps,
  ProgressIndicatorProps,
  ProgressLabelProps,
  ProgressRootProps,
  ProgressStatus,
  ProgressTrackProps,
  ProgressValueProps,
  RadioGroupOrientation,
  RadioGroupProps,
  RadioIndicatorProps,
  RadioRootProps,
  ScrollAreaContentProps,
  ScrollAreaCornerProps,
  ScrollAreaRootProps,
  ScrollAreaScrollbarProps,
  ScrollAreaThumbProps,
  ScrollAreaViewportProps,
  SelectArrowProps,
  SelectBackdropProps,
  SelectGroupLabelProps,
  SelectGroupProps,
  SelectIconProps,
  SelectItemIndicatorProps,
  SelectItemProps,
  SelectItemTextProps,
  SelectLabelProps,
  SelectListProps,
  SelectPopupProps,
  SelectPortalProps,
  SelectPositionerProps,
  SelectRootProps,
  SelectScrollDownArrowProps,
  SelectScrollUpArrowProps,
  SelectSeparatorProps,
  SelectTriggerProps,
  SelectValueProps,
  SeparatorProps,
  SimpleSelectOption,
  SimpleSelectProps,
  SliderControlProps,
  SliderIndicatorProps,
  SliderLabelProps,
  SliderRootProps,
  SliderThumbProps,
  SliderTrackProps,
  SliderValueProps,
  SwitchRootProps,
  SwitchThumbProps,
  TabsIndicatorProps,
  TabsListProps,
  TabsPanelProps,
  TabsRootProps,
  TabsTabProps,
  TextProps,
  TextareaProps,
  ThemeContextValue,
  ThemeMode,
  ThemePreference,
  ThemeProviderProps,
  ThemeResolutionInput,
  ThemeScriptProps,
  ThemeToggleProps,
  ToastActionProps,
  ToastArrowProps,
  ToastCloseProps,
  ToastContentProps,
  ToastDescriptionProps,
  ToastManager,
  // Base UI's four manager generics carry no defaults, so the tuple has to name
  // their payload types; the `Data` slot is constrained to `object`. These stay
  // presence pins — what matters is that the re-export survives, not what the
  // payload holds.
  ToastManagerAddOptions<object>,
  ToastManagerPromiseOptions<unknown, object>,
  ToastManagerUpdateOptions<object>,
  ToastNamespace,
  ToastObject<object>,
  ToastPortalProps,
  ToastPositionerProps,
  ToastProviderProps,
  ToastRootProps,
  ToastTitleProps,
  ToastViewportProps,
  ToggleGroupProps,
  ToggleProps,
  ToolbarButtonProps,
  ToolbarGroupProps,
  ToolbarInputProps,
  ToolbarLinkProps,
  ToolbarRootProps,
  ToolbarSeparatorProps,
  TooltipArrowProps,
  TooltipPopupProps,
  TooltipPortalProps,
  TooltipPositionerProps,
  TooltipProviderProps,
  TooltipRootProps,
  TooltipTriggerProps,
  TooltipViewportProps,
  UseToastManagerReturnValue,
];
