import { readdirSync, readFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

/**
 * In-app navigation is CLIENT-SIDE (Wallow-lrlm.4.3).
 *
 * A raw `<a href="/dashboard/…">` inside a mounted screen is a full document
 * load: the router tears down, every query cache is thrown away, and the visitor
 * watches a white flash on a navigation the app could have taken in place. The
 * app already knows how to do it properly — `DashboardNav`, `OrganizationList`
 * and `InquiryList` all route through TanStack `Link` — so the remaining raw
 * anchors are either a bug or a documented exception, and this spec is where the
 * difference is written down.
 *
 * **Why a spec and not a lint rule.** The rule is not "no anchors": several files
 * legitimately render plain anchors and say so in their own headers, and three
 * of the app's outbound links (`/bff/login`, the repository, the docs site)
 * SHOULD be document loads. oxlint's `no-restricted-syntax` can express "no `<a>`"
 * but not "no `<a>` at a client route, except in these files, each of which must
 * still explain itself" — which is the actual policy.
 *
 * **The exceptions, and the one thing they have in common.** `PublicLayout` and
 * the two detail back-links must render standalone — under `react-dom/server`
 * for the SSR home contract, or under a bare `QueryClientProvider` in a
 * component spec — with no router context in scope. A TanStack `Link` throws
 * there. Each file states that in its header, and this spec re-checks the
 * statement is still present so an exception cannot be inherited silently by a
 * later edit that deleted the reasoning.
 *
 * `LandingPage` is router-free for the same reason and is deliberately NOT on
 * the list: both its anchors point at an expression (`getStartedHref`, which is
 * the `/bff/login` server route, and `repositoryUrl`, which leaves the site), so
 * it renders no client-route anchor for the list to except. Adding it would make
 * the honesty case below permanently stale.
 *
 * **Known limit, deliberately.** Only STRING-LITERAL hrefs are classified; an
 * `<a href={someExpression}>` is not resolved. That is what keeps the two
 * expression hrefs above out of scope — but it also means a future anchor that
 * hides a client route behind a constant slips past. The behavioural specs
 * beside each screen are the second line of defence.
 *
 * Node project — it reads files as text and mounts nothing.
 */

const srcDir: string = dirname(fileURLToPath(import.meta.url));

/** This file is the guard; it necessarily quotes the markup it polices. */
const SELF: string = relative(srcDir, fileURLToPath(import.meta.url));

/**
 * Path prefixes that are SERVER routes, not client routes. A link to one of
 * these is meant to leave the SPA: `/bff/login` hands the browser to the OIDC
 * issuer, and `/api/*` is the passthrough proxy. Navigating either through the
 * router would be the bug.
 */
const SERVER_ROUTE_PREFIXES: readonly string[] = ["/bff/", "/api/", "/v1/", "/.well-known/"];

/**
 * The files allowed to render a raw anchor at a client route, each with the
 * reason its own header gives. Adding an entry here is a design decision: it
 * says "this component must render without a router context", which is a real
 * constraint on where the component can ever be mounted.
 */
const DOCUMENTED_ANCHOR_EXCEPTIONS: ReadonlyMap<string, string> = new Map([
  [
    "shared/components/PublicLayout.tsx",
    "public chrome renders standalone under react-dom/server, with no router in scope",
  ],
  [
    "features/organizations/components/OrganizationDetail.tsx",
    "BackLink renders under a bare QueryClientProvider in the component specs",
  ],
  [
    "features/inquiries/components/InquiryDetail.tsx",
    "the back link needs no matched route of its own, mirroring OrganizationDetail",
  ],
]);

/**
 * A marker phrase proving the file still DOCUMENTS its exception. All three
 * spellings are in the tree today ("plain anchor(s)", "renders standalone" /
 * "server-renders standalone", "router-free"), and any one is enough to show the
 * choice was deliberate rather than inherited.
 */
const EXCEPTION_MARKERS: readonly string[] = ["plain anchor", "standalone", "router-free"];

/** Directories that hold no product source. */
const SKIP_DIRS: ReadonlySet<string> = new Set(["__screenshots__", "node_modules"]);

/** Generated by the Start plugin on every dev/build — never hand-edited, never policed. */
const GENERATED: ReadonlySet<string> = new Set(["app/routeTree.gen.ts"]);

/** Each opening `<a …>` tag, up to its first `>`. */
const ANCHOR_TAG = /<a(?=[\s/>])[\s\S]*?>/gu;

/** A string-literal `href` attribute inside an opening tag. */
const LITERAL_HREF = /\shref="([^"]*)"/u;

/** A `location.assign(…)` / `location.replace(…)` / `location.href = …` navigation. */
const LOCATION_NAVIGATION =
  /\blocation\s*\.\s*(?:assign|replace)\s*\(|\blocation\s*\.\s*href\s*=[^=]/u;

/**
 * Shipped markup only. Specs render their own throwaway anchors as router stubs
 * (every `DashboardNav` spec does), and `routeTree.gen.ts` is written by the
 * Start plugin — neither is a navigation decision anyone made.
 */
function isProductFile(path: string): boolean {
  return (
    path.endsWith(".tsx") && path !== SELF && !GENERATED.has(path) && !/\.test\.tsx?$/u.test(path)
  );
}

/** Every posix path under `dir`, relative to `src/`, skipping non-source directories. */
function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const absolute: string = join(dir, entry.name);
    if (entry.isDirectory()) {
      return SKIP_DIRS.has(entry.name) ? [] : walk(absolute);
    }
    return [relative(srcDir, absolute).replaceAll("\\", "/")];
  });
}

/** Every product `.tsx` under `src/`, as posix paths relative to `src/`. */
function productFiles(): string[] {
  return walk(srcDir)
    .filter((path) => isProductFile(path))
    .toSorted();
}

/** `true` when `href` addresses a client route rather than a server route. */
function isClientRoute(href: string): boolean {
  return href.startsWith("/") && !SERVER_ROUTE_PREFIXES.some((prefix) => href.startsWith(prefix));
}

/** Every string-literal client-route href rendered by a raw `<a>` in `source`. */
function rawAnchorRoutes(source: string): string[] {
  const routes: string[] = [];
  // `</a>` never matches: the lookahead requires whitespace or a self-close
  // right after the element name. JSX attribute values in this app carry no
  // `>`, so the non-greedy stop lands on the real end of the opening tag.
  for (const [tag] of source.matchAll(ANCHOR_TAG)) {
    const href: RegExpMatchArray | null = tag.match(LITERAL_HREF);
    if (href !== null && isClientRoute(href[1] as string)) {
      routes.push(href[1] as string);
    }
  }
  return routes;
}

/** Every product file rendering a raw anchor at a client route, with its hrefs. */
function anchorOffenders(): Map<string, string[]> {
  const offenders = new Map<string, string[]>();
  for (const path of productFiles()) {
    const routes: string[] = rawAnchorRoutes(readFileSync(join(srcDir, path), "utf8"));
    if (routes.length > 0) {
      offenders.set(path, routes);
    }
  }
  return offenders;
}

describe("in-app navigation is client-side", () => {
  it("renders no raw anchor at a client route outside the documented exceptions", () => {
    const unexpected: string[] = [...anchorOffenders()]
      .filter(([path]) => !DOCUMENTED_ANCHOR_EXCEPTIONS.has(path))
      .map(([path, routes]) => `${path} -> ${routes.join(", ")}`);

    expect(
      unexpected,
      "in-app navigation must go through a TanStack `Link`/`navigate`, not a full page load",
    ).toEqual([]);
  });

  it("keeps the exception list honest — every entry still renders one", () => {
    const offenders: Map<string, string[]> = anchorOffenders();
    const stale: string[] = [...DOCUMENTED_ANCHOR_EXCEPTIONS.keys()].filter(
      (path) => !offenders.has(path),
    );

    expect(stale, "an exception that no longer renders a raw anchor must be deleted").toEqual([]);
  });

  it("requires every exception to document why it stays router-free", () => {
    const undocumented: string[] = [...DOCUMENTED_ANCHOR_EXCEPTIONS.keys()].filter((path) => {
      const source: string = readFileSync(join(srcDir, path), "utf8");
      return !EXCEPTION_MARKERS.some((marker) => source.includes(marker));
    });

    expect(undocumented, "state the router-free constraint in the file's own header").toEqual([]);
  });

  it("drives no navigation through window.location", () => {
    const offenders: string[] = productFiles().filter((path) =>
      LOCATION_NAVIGATION.test(readFileSync(join(srcDir, path), "utf8")),
    );

    expect(offenders, "a location assignment is a full page load in disguise").toEqual([]);
  });
});
