/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BffDemoRouteImport } from './routes/bff-demo'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardOrganizationsIndexRouteImport } from './routes/dashboard/organizations/index'
import { Route as DashboardInquiriesIndexRouteImport } from './routes/dashboard/inquiries/index'
import { Route as DashboardAppsIndexRouteImport } from './routes/dashboard/apps/index'
import { Route as DashboardOrganizationsOrgIdRouteImport } from './routes/dashboard/organizations/$orgId'
import { Route as DashboardInquiriesInquiryIdRouteImport } from './routes/dashboard/inquiries/$inquiryId'
import { Route as DashboardAppsRegisterRouteImport } from './routes/dashboard/apps/register'

const BffDemoRoute = BffDemoRouteImport.update({
  id: '/bff-demo',
  path: '/bff-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrganizationsIndexRoute =
  DashboardOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInquiriesIndexRoute = DashboardInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAppsIndexRoute = DashboardAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrganizationsOrgIdRoute =
  DashboardOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInquiriesInquiryIdRoute =
  DashboardInquiriesInquiryIdRouteImport.update({
    id: '/inquiries/$inquiryId',
    path: '/inquiries/$inquiryId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAppsRegisterRoute = DashboardAppsRegisterRouteImport.update({
  id: '/apps/register',
  path: '/apps/register',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/bff-demo': typeof BffDemoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/apps/register': typeof DashboardAppsRegisterRoute
  '/dashboard/inquiries/$inquiryId': typeof DashboardInquiriesInquiryIdRoute
  '/dashboard/organizations/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/dashboard/apps/': typeof DashboardAppsIndexRoute
  '/dashboard/inquiries/': typeof DashboardInquiriesIndexRoute
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/bff-demo': typeof BffDemoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/apps/register': typeof DashboardAppsRegisterRoute
  '/dashboard/inquiries/$inquiryId': typeof DashboardInquiriesInquiryIdRoute
  '/dashboard/organizations/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/dashboard/apps': typeof DashboardAppsIndexRoute
  '/dashboard/inquiries': typeof DashboardInquiriesIndexRoute
  '/dashboard/organizations': typeof DashboardOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/bff-demo': typeof BffDemoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/apps/register': typeof DashboardAppsRegisterRoute
  '/dashboard/inquiries/$inquiryId': typeof DashboardInquiriesInquiryIdRoute
  '/dashboard/organizations/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/dashboard/apps/': typeof DashboardAppsIndexRoute
  '/dashboard/inquiries/': typeof DashboardInquiriesIndexRoute
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/bff-demo'
    | '/dashboard/settings'
    | '/dashboard/apps/register'
    | '/dashboard/inquiries/$inquiryId'
    | '/dashboard/organizations/$orgId'
    | '/dashboard/apps/'
    | '/dashboard/inquiries/'
    | '/dashboard/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/bff-demo'
    | '/dashboard/settings'
    | '/dashboard/apps/register'
    | '/dashboard/inquiries/$inquiryId'
    | '/dashboard/organizations/$orgId'
    | '/dashboard/apps'
    | '/dashboard/inquiries'
    | '/dashboard/organizations'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/bff-demo'
    | '/dashboard/settings'
    | '/dashboard/apps/register'
    | '/dashboard/inquiries/$inquiryId'
    | '/dashboard/organizations/$orgId'
    | '/dashboard/apps/'
    | '/dashboard/inquiries/'
    | '/dashboard/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  BffDemoRoute: typeof BffDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bff-demo': {
      id: '/bff-demo'
      path: '/bff-demo'
      fullPath: '/bff-demo'
      preLoaderRoute: typeof BffDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organizations/': {
      id: '/dashboard/organizations/'
      path: '/organizations'
      fullPath: '/dashboard/organizations/'
      preLoaderRoute: typeof DashboardOrganizationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inquiries/': {
      id: '/dashboard/inquiries/'
      path: '/inquiries'
      fullPath: '/dashboard/inquiries/'
      preLoaderRoute: typeof DashboardInquiriesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/apps/': {
      id: '/dashboard/apps/'
      path: '/apps'
      fullPath: '/dashboard/apps/'
      preLoaderRoute: typeof DashboardAppsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organizations/$orgId': {
      id: '/dashboard/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/dashboard/organizations/$orgId'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inquiries/$inquiryId': {
      id: '/dashboard/inquiries/$inquiryId'
      path: '/inquiries/$inquiryId'
      fullPath: '/dashboard/inquiries/$inquiryId'
      preLoaderRoute: typeof DashboardInquiriesInquiryIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/apps/register': {
      id: '/dashboard/apps/register'
      path: '/apps/register'
      fullPath: '/dashboard/apps/register'
      preLoaderRoute: typeof DashboardAppsRegisterRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardAppsRegisterRoute: typeof DashboardAppsRegisterRoute
  DashboardInquiriesInquiryIdRoute: typeof DashboardInquiriesInquiryIdRoute
  DashboardOrganizationsOrgIdRoute: typeof DashboardOrganizationsOrgIdRoute
  DashboardAppsIndexRoute: typeof DashboardAppsIndexRoute
  DashboardInquiriesIndexRoute: typeof DashboardInquiriesIndexRoute
  DashboardOrganizationsIndexRoute: typeof DashboardOrganizationsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardAppsRegisterRoute: DashboardAppsRegisterRoute,
  DashboardInquiriesInquiryIdRoute: DashboardInquiriesInquiryIdRoute,
  DashboardOrganizationsOrgIdRoute: DashboardOrganizationsOrgIdRoute,
  DashboardAppsIndexRoute: DashboardAppsIndexRoute,
  DashboardInquiriesIndexRoute: DashboardInquiriesIndexRoute,
  DashboardOrganizationsIndexRoute: DashboardOrganizationsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  BffDemoRoute: BffDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
