apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: foundry
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 1000m
