apiRules:
- exclude:
    uidRegex: ^.*\.Infrastructure.*$
    type: Namespace
- exclude:
    uidRegex: ^.*\.Infrastructure.*$
    type: Class
- exclude:
    uidRegex: ^.*\.Infrastructure.*$
    type: Type
