apiVersion: 1
datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - name: TraceID
          matcherType: label
          matcherRegex: trace_id
          datasourceUid: tempo
          url: "$${__value.raw}"
        - name: BrowserTraceID
          matcherRegex: '(?:traceID|trace_id|traceId)="?([a-f0-9]{32})'
          datasourceUid: tempo
          url: "$${__value.raw}"
    editable: false
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
        customQuery: true
        query: '{service_name=~".+"} | logfmt | trace_id="$${__trace.traceId}" or traceID="$${__trace.traceId}"'
      nodeGraph:
        enabled: true
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
    editable: false
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
