apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallow
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: wallow
          resources:
            requests:
              memory: 512Mi
              cpu: 1000m
            limits:
              memory: 1Gi
              cpu: 2000m
