export {
  AlertDialog,
  type AlertDialogBackdropProps,
  type AlertDialogCloseProps,
  type AlertDialogDescriptionProps,
  type AlertDialogPopupProps,
  type AlertDialogPortalProps,
  type AlertDialogRootProps,
  type AlertDialogTitleProps,
  type AlertDialogTriggerProps,
  type AlertDialogViewportProps,
} from "./alert-dialog";
export {
  alertDialogBackdropRecipe,
  type AlertDialogBackdropRecipeProps,
  alertDialogCloseRecipe,
  type AlertDialogCloseRecipeProps,
  alertDialogDescriptionRecipe,
  type AlertDialogDescriptionRecipeProps,
  alertDialogPopupRecipe,
  type AlertDialogPopupRecipeProps,
  alertDialogTitleRecipe,
  type AlertDialogTitleRecipeProps,
  alertDialogTriggerRecipe,
  type AlertDialogTriggerRecipeProps,
  alertDialogViewportRecipe,
  type AlertDialogViewportRecipeProps,
} from "./alert-dialog.styles";
