/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BffDemoRouteImport } from './routes/bff-demo'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as BffSplatRouteImport } from './routes/bff/$'
import { Route as BffLogsRouteImport } from './routes/bff/logs'
import { Route as DashboardMyOrganizationsRouteImport } from './routes/dashboard/my-organizations'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardInquiriesIndexRouteImport } from './routes/dashboard/inquiries/index'
import { Route as DashboardInquiriesInquiryIdRouteImport } from './routes/dashboard/inquiries/$inquiryId'
import { Route as DashboardOrganizationsIndexRouteImport } from './routes/dashboard/organizations/index'
import { Route as DashboardOrganizationsInvitationsRouteImport } from './routes/dashboard/organizations/invitations'
import { Route as DashboardOrganizationsOrgIdIndexRouteImport } from './routes/dashboard/organizations/$orgId/index'
import { Route as DashboardOrganizationsOrgIdMembersRouteImport } from './routes/dashboard/organizations/$orgId/members'
import { Route as DashboardOrganizationsOrgIdRequestsRouteImport } from './routes/dashboard/organizations/$orgId/requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BffDemoRoute = BffDemoRouteImport.update({
  id: '/bff-demo',
  path: '/bff-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BffSplatRoute = BffSplatRouteImport.update({
  id: '/bff/$',
  path: '/bff/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BffLogsRoute = BffLogsRouteImport.update({
  id: '/bff/logs',
  path: '/bff/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMyOrganizationsRoute =
  DashboardMyOrganizationsRouteImport.update({
    id: '/my-organizations',
    path: '/my-organizations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInquiriesIndexRoute = DashboardInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInquiriesInquiryIdRoute =
  DashboardInquiriesInquiryIdRouteImport.update({
    id: '/inquiries/$inquiryId',
    path: '/inquiries/$inquiryId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrganizationsIndexRoute =
  DashboardOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrganizationsInvitationsRoute =
  DashboardOrganizationsInvitationsRouteImport.update({
    id: '/organizations/invitations',
    path: '/organizations/invitations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrganizationsOrgIdIndexRoute =
  DashboardOrganizationsOrgIdIndexRouteImport.update({
    id: '/organizations/$orgId/',
    path: '/organizations/$orgId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrganizationsOrgIdMembersRoute =
  DashboardOrganizationsOrgIdMembersRouteImport.update({
    id: '/organizations/$orgId/members',
    path: '/organizations/$orgId/members',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrganizationsOrgIdRequestsRoute =
  DashboardOrganizationsOrgIdRequestsRouteImport.update({
    id: '/organizations/$orgId/requests',
    path: '/organizations/$orgId/requests',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/bff-demo': typeof BffDemoRoute
  '/health': typeof HealthRoute
  '/api/$': typeof ApiSplatRoute
  '/bff/$': typeof BffSplatRoute
  '/bff/logs': typeof BffLogsRoute
  '/dashboard/my-organizations': typeof DashboardMyOrganizationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/inquiries/$inquiryId': typeof DashboardInquiriesInquiryIdRoute
  '/dashboard/organizations/invitations': typeof DashboardOrganizationsInvitationsRoute
  '/dashboard/inquiries/': typeof DashboardInquiriesIndexRoute
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
  '/dashboard/organizations/$orgId/members': typeof DashboardOrganizationsOrgIdMembersRoute
  '/dashboard/organizations/$orgId/requests': typeof DashboardOrganizationsOrgIdRequestsRoute
  '/dashboard/organizations/$orgId/': typeof DashboardOrganizationsOrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/bff-demo': typeof BffDemoRoute
  '/health': typeof HealthRoute
  '/api/$': typeof ApiSplatRoute
  '/bff/$': typeof BffSplatRoute
  '/bff/logs': typeof BffLogsRoute
  '/dashboard/my-organizations': typeof DashboardMyOrganizationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/inquiries/$inquiryId': typeof DashboardInquiriesInquiryIdRoute
  '/dashboard/organizations/invitations': typeof DashboardOrganizationsInvitationsRoute
  '/dashboard/inquiries': typeof DashboardInquiriesIndexRoute
  '/dashboard/organizations': typeof DashboardOrganizationsIndexRoute
  '/dashboard/organizations/$orgId/members': typeof DashboardOrganizationsOrgIdMembersRoute
  '/dashboard/organizations/$orgId/requests': typeof DashboardOrganizationsOrgIdRequestsRoute
  '/dashboard/organizations/$orgId': typeof DashboardOrganizationsOrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/bff-demo': typeof BffDemoRoute
  '/health': typeof HealthRoute
  '/api/$': typeof ApiSplatRoute
  '/bff/$': typeof BffSplatRoute
  '/bff/logs': typeof BffLogsRoute
  '/dashboard/my-organizations': typeof DashboardMyOrganizationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/inquiries/$inquiryId': typeof DashboardInquiriesInquiryIdRoute
  '/dashboard/organizations/invitations': typeof DashboardOrganizationsInvitationsRoute
  '/dashboard/inquiries/': typeof DashboardInquiriesIndexRoute
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
  '/dashboard/organizations/$orgId/members': typeof DashboardOrganizationsOrgIdMembersRoute
  '/dashboard/organizations/$orgId/requests': typeof DashboardOrganizationsOrgIdRequestsRoute
  '/dashboard/organizations/$orgId/': typeof DashboardOrganizationsOrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/bff-demo'
    | '/health'
    | '/api/$'
    | '/bff/$'
    | '/bff/logs'
    | '/dashboard/my-organizations'
    | '/dashboard/settings'
    | '/dashboard/inquiries/$inquiryId'
    | '/dashboard/organizations/invitations'
    | '/dashboard/inquiries/'
    | '/dashboard/organizations/'
    | '/dashboard/organizations/$orgId/members'
    | '/dashboard/organizations/$orgId/requests'
    | '/dashboard/organizations/$orgId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/bff-demo'
    | '/health'
    | '/api/$'
    | '/bff/$'
    | '/bff/logs'
    | '/dashboard/my-organizations'
    | '/dashboard/settings'
    | '/dashboard/inquiries/$inquiryId'
    | '/dashboard/organizations/invitations'
    | '/dashboard/inquiries'
    | '/dashboard/organizations'
    | '/dashboard/organizations/$orgId/members'
    | '/dashboard/organizations/$orgId/requests'
    | '/dashboard/organizations/$orgId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/bff-demo'
    | '/health'
    | '/api/$'
    | '/bff/$'
    | '/bff/logs'
    | '/dashboard/my-organizations'
    | '/dashboard/settings'
    | '/dashboard/inquiries/$inquiryId'
    | '/dashboard/organizations/invitations'
    | '/dashboard/inquiries/'
    | '/dashboard/organizations/'
    | '/dashboard/organizations/$orgId/members'
    | '/dashboard/organizations/$orgId/requests'
    | '/dashboard/organizations/$orgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  BffDemoRoute: typeof BffDemoRoute
  HealthRoute: typeof HealthRoute
  ApiSplatRoute: typeof ApiSplatRoute
  BffSplatRoute: typeof BffSplatRoute
  BffLogsRoute: typeof BffLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bff-demo': {
      id: '/bff-demo'
      path: '/bff-demo'
      fullPath: '/bff-demo'
      preLoaderRoute: typeof BffDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bff/$': {
      id: '/bff/$'
      path: '/bff/$'
      fullPath: '/bff/$'
      preLoaderRoute: typeof BffSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bff/logs': {
      id: '/bff/logs'
      path: '/bff/logs'
      fullPath: '/bff/logs'
      preLoaderRoute: typeof BffLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/my-organizations': {
      id: '/dashboard/my-organizations'
      path: '/my-organizations'
      fullPath: '/dashboard/my-organizations'
      preLoaderRoute: typeof DashboardMyOrganizationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inquiries/': {
      id: '/dashboard/inquiries/'
      path: '/inquiries'
      fullPath: '/dashboard/inquiries/'
      preLoaderRoute: typeof DashboardInquiriesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inquiries/$inquiryId': {
      id: '/dashboard/inquiries/$inquiryId'
      path: '/inquiries/$inquiryId'
      fullPath: '/dashboard/inquiries/$inquiryId'
      preLoaderRoute: typeof DashboardInquiriesInquiryIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organizations/': {
      id: '/dashboard/organizations/'
      path: '/organizations'
      fullPath: '/dashboard/organizations/'
      preLoaderRoute: typeof DashboardOrganizationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organizations/invitations': {
      id: '/dashboard/organizations/invitations'
      path: '/organizations/invitations'
      fullPath: '/dashboard/organizations/invitations'
      preLoaderRoute: typeof DashboardOrganizationsInvitationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organizations/$orgId/': {
      id: '/dashboard/organizations/$orgId/'
      path: '/organizations/$orgId'
      fullPath: '/dashboard/organizations/$orgId/'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organizations/$orgId/members': {
      id: '/dashboard/organizations/$orgId/members'
      path: '/organizations/$orgId/members'
      fullPath: '/dashboard/organizations/$orgId/members'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdMembersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organizations/$orgId/requests': {
      id: '/dashboard/organizations/$orgId/requests'
      path: '/organizations/$orgId/requests'
      fullPath: '/dashboard/organizations/$orgId/requests'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdRequestsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardMyOrganizationsRoute: typeof DashboardMyOrganizationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardInquiriesInquiryIdRoute: typeof DashboardInquiriesInquiryIdRoute
  DashboardOrganizationsInvitationsRoute: typeof DashboardOrganizationsInvitationsRoute
  DashboardInquiriesIndexRoute: typeof DashboardInquiriesIndexRoute
  DashboardOrganizationsIndexRoute: typeof DashboardOrganizationsIndexRoute
  DashboardOrganizationsOrgIdMembersRoute: typeof DashboardOrganizationsOrgIdMembersRoute
  DashboardOrganizationsOrgIdRequestsRoute: typeof DashboardOrganizationsOrgIdRequestsRoute
  DashboardOrganizationsOrgIdIndexRoute: typeof DashboardOrganizationsOrgIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardMyOrganizationsRoute: DashboardMyOrganizationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardInquiriesInquiryIdRoute: DashboardInquiriesInquiryIdRoute,
  DashboardOrganizationsInvitationsRoute:
    DashboardOrganizationsInvitationsRoute,
  DashboardInquiriesIndexRoute: DashboardInquiriesIndexRoute,
  DashboardOrganizationsIndexRoute: DashboardOrganizationsIndexRoute,
  DashboardOrganizationsOrgIdMembersRoute:
    DashboardOrganizationsOrgIdMembersRoute,
  DashboardOrganizationsOrgIdRequestsRoute:
    DashboardOrganizationsOrgIdRequestsRoute,
  DashboardOrganizationsOrgIdIndexRoute: DashboardOrganizationsOrgIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  BffDemoRoute: BffDemoRoute,
  HealthRoute: HealthRoute,
  ApiSplatRoute: ApiSplatRoute,
  BffSplatRoute: BffSplatRoute,
  BffLogsRoute: BffLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
