using System.Diagnostics;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

string root = Path.GetFullPath(args[0]);
string baseline = args.Length > 1 ? args[1] : "258f27eabbe6676598a79097ff99cae899dc0e81";
HashSet<string> recorded = File.ReadLines(Path.Combine(root, "docs/agents/api-comment-review-233/comments.tsv"))
    .Skip(1).Select(line => line.Split('\t')).Where(parts => parts[0].EndsWith(".cs", StringComparison.Ordinal))
    .Select(parts => parts[0] + ":" + parts[1]).ToHashSet(StringComparer.Ordinal);
HashSet<string> observed = new(StringComparer.Ordinal);
int changed = 0;
int total = 0;
foreach (string path in Git("ls-files", "api").Split('\n', StringSplitOptions.RemoveEmptyEntries)
             .Where(path => path.EndsWith(".cs", StringComparison.Ordinal)))
{
    string before = Git("show", baseline + ":" + path);
    string after = File.ReadAllText(Path.Combine(root, path));
    SyntaxNode oldTree = CSharpSyntaxTree.ParseText(before).GetRoot();
    SyntaxNode newTree = CSharpSyntaxTree.ParseText(after).GetRoot();
    foreach (SyntaxTrivia trivia in oldTree.DescendantTrivia(descendIntoTrivia: true).Where(IsComment))
    {
        int line = oldTree.SyntaxTree.GetLineSpan(trivia.Span).StartLinePosition.Line + 1;
        observed.Add(path + ":" + line);
    }
    if (Tokens(oldTree) != Tokens(newTree) || Special(oldTree) != Special(newTree) || Protected(oldTree) != Protected(newTree))
    {
        throw new InvalidOperationException("Non-prose change: " + path);
    }
    if (before != after)
    {
        changed++;
    }
    total++;
}
if (!recorded.SetEquals(observed))
{
    throw new InvalidOperationException("C# baseline comment inventory does not match comments.tsv.");
}
Console.WriteLine($"PASS: {total} C# files ({changed} changed) preserve executable tokens/literals, disabled text, directives and protected comment placement; {observed.Count} baseline comments accounted for.");

string Git(params string[] arguments)
{
    ProcessStartInfo info = new("git") { WorkingDirectory = root, RedirectStandardOutput = true };
    foreach (string argument in arguments)
    {
        info.ArgumentList.Add(argument);
    }
    using Process process = Process.Start(info) ?? throw new InvalidOperationException("Could not start git.");
    string output = process.StandardOutput.ReadToEnd();
    process.WaitForExit();
    if (process.ExitCode != 0)
    {
        throw new InvalidOperationException("git failed.");
    }
    return output;
}

static bool IsComment(SyntaxTrivia trivia) => trivia.Kind() is SyntaxKind.SingleLineCommentTrivia
    or SyntaxKind.MultiLineCommentTrivia or SyntaxKind.SingleLineDocumentationCommentTrivia
    or SyntaxKind.MultiLineDocumentationCommentTrivia;

static string Tokens(SyntaxNode node) => JsonSerializer.Serialize(node.DescendantTokens()
    .Select(token => new { kind = token.RawKind, text = token.Text }));

static string Special(SyntaxNode node) => JsonSerializer.Serialize(node.DescendantTrivia(descendIntoTrivia: true)
    .Where(trivia => trivia.IsDirective || trivia.IsKind(SyntaxKind.DisabledTextTrivia) || trivia.IsKind(SyntaxKind.SkippedTokensTrivia))
    .Select(trivia => new
    {
        kind = trivia.RawKind,
        text = trivia.IsDirective
            ? string.Join("|", trivia.GetStructure()!.DescendantTokens().Select(token => token.Text))
            : trivia.ToFullString()
    }));

static string Protected(SyntaxNode node)
{
    SyntaxToken[] tokens = node.DescendantTokens().ToArray();
    return JsonSerializer.Serialize(node.DescendantTrivia(descendIntoTrivia: true)
        .Where(trivia => trivia.ToString().StartsWith("// ReSharper", StringComparison.Ordinal)
                         || trivia.ToString().Contains("<auto-generated", StringComparison.Ordinal)
                         || trivia.ToString().StartsWith("// Copyright", StringComparison.Ordinal))
        .Select(trivia => new
        {
            text = trivia.ToFullString(),
            next = Array.FindIndex(tokens, token => token.SpanStart >= trivia.FullSpan.End)
        }));
}
