/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptTermsRouteImport } from './routes/accept-terms'
import { Route as AccessRequestRouteImport } from './routes/access-request'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HealthRouteImport } from './routes/health'
import { Route as InvitationRouteImport } from './routes/invitation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DotwellKnownSplatRouteImport } from './routes/[.]well-known/$'
import { Route as ConnectSplatRouteImport } from './routes/connect/$'
import { Route as MfaChallengeRouteImport } from './routes/mfa/challenge'
import { Route as MfaEnrollRouteImport } from './routes/mfa/enroll'
import { Route as V1SplatRouteImport } from './routes/v1/$'
import { Route as VerifyEmailIndexRouteImport } from './routes/verify-email/index'
import { Route as VerifyEmailConfirmRouteImport } from './routes/verify-email/confirm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptTermsRoute = AcceptTermsRouteImport.update({
  id: '/accept-terms',
  path: '/accept-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRequestRoute = AccessRequestRouteImport.update({
  id: '/access-request',
  path: '/access-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationRoute = InvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownSplatRoute = DotwellKnownSplatRouteImport.update({
  id: '/.well-known/$',
  path: '/.well-known/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectSplatRoute = ConnectSplatRouteImport.update({
  id: '/connect/$',
  path: '/connect/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaChallengeRoute = MfaChallengeRouteImport.update({
  id: '/mfa/challenge',
  path: '/mfa/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaEnrollRoute = MfaEnrollRouteImport.update({
  id: '/mfa/enroll',
  path: '/mfa/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SplatRoute = V1SplatRouteImport.update({
  id: '/v1/$',
  path: '/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailIndexRoute = VerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailConfirmRoute = VerifyEmailConfirmRouteImport.update({
  id: '/verify-email/confirm',
  path: '/verify-email/confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/access-request': typeof AccessRequestRoute
  '/consent': typeof ConsentRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/logs': typeof LogsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/connect/$': typeof ConnectSplatRoute
  '/mfa/challenge': typeof MfaChallengeRoute
  '/mfa/enroll': typeof MfaEnrollRoute
  '/v1/$': typeof V1SplatRoute
  '/verify-email/confirm': typeof VerifyEmailConfirmRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/access-request': typeof AccessRequestRoute
  '/consent': typeof ConsentRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/logs': typeof LogsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/connect/$': typeof ConnectSplatRoute
  '/mfa/challenge': typeof MfaChallengeRoute
  '/mfa/enroll': typeof MfaEnrollRoute
  '/v1/$': typeof V1SplatRoute
  '/verify-email/confirm': typeof VerifyEmailConfirmRoute
  '/verify-email': typeof VerifyEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/access-request': typeof AccessRequestRoute
  '/consent': typeof ConsentRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/logs': typeof LogsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/connect/$': typeof ConnectSplatRoute
  '/mfa/challenge': typeof MfaChallengeRoute
  '/mfa/enroll': typeof MfaEnrollRoute
  '/v1/$': typeof V1SplatRoute
  '/verify-email/confirm': typeof VerifyEmailConfirmRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-terms'
    | '/access-request'
    | '/consent'
    | '/error'
    | '/forgot-password'
    | '/health'
    | '/invitation'
    | '/login'
    | '/logout'
    | '/logs'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/terms'
    | '/.well-known/$'
    | '/connect/$'
    | '/mfa/challenge'
    | '/mfa/enroll'
    | '/v1/$'
    | '/verify-email/confirm'
    | '/verify-email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-terms'
    | '/access-request'
    | '/consent'
    | '/error'
    | '/forgot-password'
    | '/health'
    | '/invitation'
    | '/login'
    | '/logout'
    | '/logs'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/terms'
    | '/.well-known/$'
    | '/connect/$'
    | '/mfa/challenge'
    | '/mfa/enroll'
    | '/v1/$'
    | '/verify-email/confirm'
    | '/verify-email'
  id:
    | '__root__'
    | '/'
    | '/accept-terms'
    | '/access-request'
    | '/consent'
    | '/error'
    | '/forgot-password'
    | '/health'
    | '/invitation'
    | '/login'
    | '/logout'
    | '/logs'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/terms'
    | '/.well-known/$'
    | '/connect/$'
    | '/mfa/challenge'
    | '/mfa/enroll'
    | '/v1/$'
    | '/verify-email/confirm'
    | '/verify-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptTermsRoute: typeof AcceptTermsRoute
  AccessRequestRoute: typeof AccessRequestRoute
  ConsentRoute: typeof ConsentRoute
  ErrorRoute: typeof ErrorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthRoute: typeof HealthRoute
  InvitationRoute: typeof InvitationRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  LogsRoute: typeof LogsRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  TermsRoute: typeof TermsRoute
  DotwellKnownSplatRoute: typeof DotwellKnownSplatRoute
  ConnectSplatRoute: typeof ConnectSplatRoute
  MfaChallengeRoute: typeof MfaChallengeRoute
  MfaEnrollRoute: typeof MfaEnrollRoute
  V1SplatRoute: typeof V1SplatRoute
  VerifyEmailConfirmRoute: typeof VerifyEmailConfirmRoute
  VerifyEmailIndexRoute: typeof VerifyEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-terms': {
      id: '/accept-terms'
      path: '/accept-terms'
      fullPath: '/accept-terms'
      preLoaderRoute: typeof AcceptTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-request': {
      id: '/access-request'
      path: '/access-request'
      fullPath: '/access-request'
      preLoaderRoute: typeof AccessRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation': {
      id: '/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof InvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/$': {
      id: '/.well-known/$'
      path: '/.well-known/$'
      fullPath: '/.well-known/$'
      preLoaderRoute: typeof DotwellKnownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$': {
      id: '/connect/$'
      path: '/connect/$'
      fullPath: '/connect/$'
      preLoaderRoute: typeof ConnectSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/challenge': {
      id: '/mfa/challenge'
      path: '/mfa/challenge'
      fullPath: '/mfa/challenge'
      preLoaderRoute: typeof MfaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/enroll': {
      id: '/mfa/enroll'
      path: '/mfa/enroll'
      fullPath: '/mfa/enroll'
      preLoaderRoute: typeof MfaEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/$': {
      id: '/v1/$'
      path: '/v1/$'
      fullPath: '/v1/$'
      preLoaderRoute: typeof V1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/': {
      id: '/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof VerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/confirm': {
      id: '/verify-email/confirm'
      path: '/verify-email/confirm'
      fullPath: '/verify-email/confirm'
      preLoaderRoute: typeof VerifyEmailConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptTermsRoute: AcceptTermsRoute,
  AccessRequestRoute: AccessRequestRoute,
  ConsentRoute: ConsentRoute,
  ErrorRoute: ErrorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthRoute: HealthRoute,
  InvitationRoute: InvitationRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  LogsRoute: LogsRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  TermsRoute: TermsRoute,
  DotwellKnownSplatRoute: DotwellKnownSplatRoute,
  ConnectSplatRoute: ConnectSplatRoute,
  MfaChallengeRoute: MfaChallengeRoute,
  MfaEnrollRoute: MfaEnrollRoute,
  V1SplatRoute: V1SplatRoute,
  VerifyEmailConfirmRoute: VerifyEmailConfirmRoute,
  VerifyEmailIndexRoute: VerifyEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
